/*
 * This source file was generated by the Gradle 'init' task
 */

import mw.iotdevices.Fan;
import mw.iotdevices.IoTDevice;

public class Main {
    public static void main(String[] args) {
       IoTDevice device1 = new Fan("Kitchen", 50);
       System.out.println(device1.identify());
    }
}
